services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-app:1.0
    # We remove 'container_name' and 'ports' so Docker can spin up multiple isolated replicas safely!
    env_file:
      - .env.local
    restart: unless-stopped

  # Our Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - terminal
    restart: unless-stopped

  terminal:
    build:
      context: ./terminal-server
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # Phase 7: Observability
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
