events {
    worker_connections 1024;
}

http {
    upstream nextjs_cluster {
        # The 'web' hostname is automatically resolved by Docker to all replicas
        server web:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nextjs_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_addrm_x_forwarded_for;
        }
    }
}
