events {
    worker_connections 1024;
}

http {
    upstream nextjs_cluster {
        # The 'web' hostname is automatically resolved by Docker to all replicas
        server web:3000;
    }

    upstream terminal_server {
        server terminal:4000;
    }

    server {
        listen 80;

        location /api/terminal/ {
            proxy_pass http://terminal_server/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_addrm_x_forwarded_for;
        }

        location / {
            proxy_pass http://nextjs_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_addrm_x_forwarded_for;
        }
    }
}
